version: "3"

services:
  pagila:
    image: ${POSTGRESQL_IMAGE}:${POSTGRESQL_VERSION}
    container_name: ${POSTGRESQL_CONTAINER_NAME}-1
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
    volumes:
      - type: bind
        source: ${PROJECT_HOME}/${SCHEMA_SCRIPT_PATH}
        target: ${ENTRYPOINT_DIRECTORY_PATH}/1-pagila-schema.sql
      - type: bind
        source:  ${PROJECT_HOME}/${DATA_SCRIPT_PATH}
        target: ${ENTRYPOINT_DIRECTORY_PATH}/2-pagila-data.sql
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    expose:
      - ${CONTAINER_PORT}
    command: -p ${CONTAINER_PORT}